apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-ci-cd-k8s-deployment
  labels:
    app: node-ci-cd-k8s
spec:
  replicas: 3
  selector:
    matchLabels:
      app: node-ci-cd-k8s
  template:
    metadata:
      labels:
        app: node-ci-cd-k8s
    spec:
      containers:
      - name: node-ci-cd-k8s-container
        image: snehakurve7/node-ci-cd-k8s:latest
        ports:
        - containerPort: 3000
        env:
        - name: NODE_ENV
          value: "production"
        readinessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 10
          periodSeconds: 5
        livenessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 30
          periodSeconds: 10
      restartPolicy: Always

---
apiVersion: v1
kind: Service
metadata:
  name: node-ci-cd-k8s-service
spec:
  selector:
    app: node-ci-cd-k8s
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: LoadBalancer
</content>
</create_file>
