apiVersion: v1
kind: Service
metadata:
  name: node-ci-cd-k8s-service
spec:
  type: LoadBalancer
  selector:
    app: node-ci-cd-k8s
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000

